### ISSUE TITLE
task list

### ISSUE THREAD

**Issue by marvinmin** [UBC-MDS/DSCI532_Group112_Unemployment#14]
- [x] build another branch `milestone2` and deploy the app from the new branch

- [x] code for tab2

- [x] code for tab3

- [x]  make the tabs work

- [x] use slider to choose the year range

- [x] use checklist to choose industries list

- [x] use the radio button to choose the stat

- [x] make the tooltip better

- [x] make the app look nicer

- [x] documentation about the functionality of the app

- [x] reflection (<500 words)
